project:
  type: website
  output-dir: _site

website:
  title: "Mangiamele Lab RNA-seq tutorial"
  description: "A practical, beginner-friendly tutorial for running nf-core/rnaseq."
  site-url: "https://katarinafloer.github.io/tutorial-nfcore-rnaseq/"
  repo-url: "https://github.com/katarinafloer/tutorial-nfcore-rnaseq"
  repo-actions: [edit, issue]
  search:
    location: sidebar
    type: textbox
  sidebar:
    style: docked
    contents:
      - index.qmd
      - rna-seq-concepts.qmd
      - file-types-storage.qmd
      - connecting-to-unity.qmd
      - setup.qmd
      - running.qmd
      - results.qmd
      - troubleshooting.qmd
  page-footer:
    left: "Maintained by Katarina Flöer"
    right: "<span class=\"last-updated\">Last updated: AUTO_LAST_UPDATED</span>"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    toc-depth: 3
    number-sections: true
    code-copy: true
    code-overflow: wrap
    page-layout: full

execute:
  freeze: auto
